# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'RealmFlatTrial' do

pod 'RealmSwift'
pod 'TQLocationConverter', :git => 'https://github.com/TinyQ/TQLocationConverter.git'

end

